### ISSUE TITLE
Insubstantial 7.2 does not anti-alias text

### ISSUE THREAD

**Issue by bobbylight** [Insubstantial/insubstantial#100]
Whereas Insubstantial 7.1 anti-aliased all text in the UI, 7.2 does not.  Unfortunately, this will probably cause many folks to stay on 7.1.

**Comment by Stephane-D** [comment]
+1
Fresh compiling on the last version, some texts are not anymore anti-aliased which is a big issue for us.
It's impossible to trace from where the problem come as i believe the anti aliasing in done in augmented part of code...

**Comment by shemnon** [comment]
Looks to be addressed by #101.  Please leave a comment if I am mistaken.
