### ISSUE TITLE
Rounded corners bug on JInternalFrame

### ISSUE THREAD

**Issue by Stephane-D** [Insubstantial/insubstantial#104]
In the last 7.2.1 snapshot, the JInternalFrame opaque property is always set to true even when rounded corners are enabled which lead to having wrong corner rendering.

Before:
![Before](http://images4.hiboox.com/images/4512/43f41bf147998557ee9a8a1f0a673d4e.jpg)

After :
![After](http://images4.hiboox.com/images/4512/476e996949e2f57a15393340f75ba90d.jpg)

**Comment by shemnon** [comment]
Looks like #90 caused this.  I am reverting #90 and un-milestoneing it.

**Comment by Stephane-D** [comment]
Yep, but because of a wrong #90 fix (no need to revert it).
