### ISSUE TITLE
Creme skin not support Myanmar language

### ISSUE THREAD

**Issue by svininykh** [Insubstantial/insubstantial#134]
This is problem relation with any skins of Insubstantial Swing look-and-feel library. The temporary solution is setting System or Metal theme skin.

Myanmar language UTF string for testing: မြန်မာဘာသာ

![Myanmar language Bug](https://cloud.githubusercontent.com/assets/1005780/5993160/b7affdf8-aa70-11e4-83bb-4635e0adc489.png)

**Comment by ritschwumm** [comment]
looks like the font being used doesn't support it

**Comment by svininykh** [comment]
So sorry, font problem. I set UIManager Serif font and problem resolve.
