### ISSUE TITLE
Support orderly shutdown of animation and callback threads

### ISSUE THREAD

**Issue by jerith666** [Insubstantial/insubstantial#18]
We need a way to shutdown the two threads started by TimelineEngine.  They're keeping old ClassLoaders in memory and causing PermGen OOMEs in our application.

**Comment by shemnon** [comment]
If the threads shut down when there are no callbacks or timelines running, would that be sufficient?

**Comment by jerith666** [comment]
Yes, this should do the trick.  Thanks!
