### ISSUE TITLE
Deal with SwingX 1.6.2

### ISSUE THREAD

**Issue by flynnk** [Insubstantial/insubstantial#32]
A quick glance at central hints that SwingX changed it's artifact id to swingx-core from swingx.  If we put the latest swingx on our path and substance-swingx, bad things ensue.

Are there plans to update to SwingX 1.6.2 or are there reasons why we might not want to in terms of incompatibilities?  Of course, there is the constant question of whether or not SwingX is even alive anymore...

At minimum, this is probably going to require some documentation?

**Comment by shemnon** [comment]
I'll look into using the latest swingx in the insubstantial 7.0 release.  My guess is that there are some generics related signature changes.

**Comment by flynnk** [comment]
Cool.  For now I'm just holding off on 1.6.2--I have no actual need for it other than just going through and updating everything.  :)

Thanks!  And thanks for maintaining this stuff as always.  :)
