### ISSUE TITLE
asm:asm-all dependency

### ISSUE THREAD

**Issue by flynnk** [Insubstantial/insubstantial#45]
... breaks groovy if on the same classpath.  This was present in 6.2.

**Comment by shemnon** [comment]
Have you tried 7.0?  I changed ASM to provided in the most current release.  And yes, this is a change from 6.2.

**Comment by flynnk** [comment]
I have not tried 7.0 yet; going to go through the core libraries of all our stuff next week and update things (new Guava is out, all the insubstantial stuff, etc.).

What provides it?

**Comment by shemnon** [comment]
provided is a maven thing that says "compile with this but don't ship it."
 That and ant are the two provides.  They are only needed for build time
stuff, perhaps I should strip it into a classified version of the jar that
includes the ant task and such.

On Fri, Oct 28, 2011 at 3:28 PM, flynnk <
reply@reply.github.com>wrote:

> I have not tried 7.0 yet; going to go through the core libraries of all our
> stuff next week and update things (new Guava is out, all the insubstantial
> stuff, etc.).
> 
> What provides it?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Insubstantial/insubstantial/issues/45#issuecomment-2561412

## 

---

"But you didn't." - Jim Halpert, The Office S05E23

**Comment by flynnk** [comment]
I think the "maven way" here is to have a separate artifact that has that dependency that would be included on the dependency path for some sort of maven plugin.  "provided" means it has to be there at runtime.  It's really meant for things that have some sort of plugin framework (like J2EE container built in dependencies, or we have our own plugin framework for our apps that does provided for stuff).

What actually requires the ant and asm stuff?  I seem to remember there being a blog about it a couple of years ago, but we apparently don't use that part of things...

**Comment by shemnon** [comment]
laf-widget or laf-plugin, not sure which.  They do some post compile processing to do some boilerplate stuff for complex but repetitive things like shadows that isn't ameniable to cut and paste.

**Comment by flynnk** [comment]
Does it need to be a dependency at all?

**Comment by flynnk** [comment]
Did you also mark ant as provided or drop the dependency?  That is currently (6.2) yanked in by laf-widget, which seems to be the case in the latest gradle trunk.

**Comment by shemnon** [comment]
Marked as provided.
On Nov 16, 2011 9:04 PM, "flynnk" <
reply@reply.github.com>
wrote:

**Comment by flynnk** [comment]
Cool.  Thanks!
