### ISSUE TITLE
Lite distribution contains missing references

### ISSUE THREAD

**Issue by nroduit** [Insubstantial/insubstantial#54]
When building the lite distribution the package 'org/pushingpixels/substance/internal/contrib/randelshofer/**' are excluded, but the class org/pushingpixels/substance/internal/plugin/BasePlugin.java still has several imports from randelshofer package.

To get a clean distribution, I also remove the class BasePlugin and the its registration in /resources/META-INF/substance-plugin.xml (Java service).

**Comment by shemnon** [comment]
Removing the class from plugin.xml creates a lot of build headaches I don't think are worth managing.

The referenced classes are from a method that is not referenced anywhere in the code, so I removed the method and the classes.  It should load fine under strict verification now.
