### ISSUE TITLE
Incorrect animation for when active tab of JTabbedPane loses focus

### ISSUE THREAD

**Issue by cowwoc** [Insubstantial/insubstantial#55]
1. Display a JTabbedPane under the "Business" skin.
2. Move the mouse over a deactivated tab. Notice how it fades in.
3. Move the mouse away from the deactivated tab. Notice how it fades out.
4. Now, move the mouse over the active tab. Notice how it plays the same animation as a deactivated tab (starting from a darker color than an active tab should ever be). The animation looks wrong, as if it is flickering.
5. The same problem occurs when you move out of the tab (it fades into the color of a deactivated tab, then "jumps" to the correct color).

**Comment by PirolA** [comment]
The same is also struck me. It is disturbing!
Did somebody find a solution?

**Comment by PirolA** [comment]
The problem already occur in the current trunk.
When you move out of the tab the tab flickers.

Regards
PirolA
