### ISSUE TITLE
No more repaint on JFrame after minimization on OS X 10.7 (Lion)

### ISSUE THREAD

**Issue by Stephane-D** [Insubstantial/insubstantial#57]
The content of a JFrame is no more repainted after it has been minimized (then restored). 
If you resize the JFrame this somewhat force the repaint so you can see the application is still alive.
The bug happens only on MAC OS X 10.7 (Lion).
It's also present in the original Substance LAF and Metal LAF but not with system, motif or nimbus LAF.

**Comment by shemnon** [comment]
Unless a patch comes from the community I don't see this issue being addressed.

**Comment by Stephane-D** [comment]
Thanks for your very fast reply !
Indeed i just tested and the problem comes from the JFrame.setDefaultLookAndFeelDecorated(true).
If we set it to false (but still using the LAF) then the problem disappears.

Edit : Afaik it comes from the JFrame.setUndecorated(true);
Even without LAF, setting this make the problem to happen so you can close the issue, sorry ;)

**Comment by chilloutman** [comment]
@Stephane-D Have you been able to solve this issue? Isn't the problem somehow related to the LAF? I couldn't find any other reports of it, except this one...

**Comment by Stephane-D** [comment]
Unfortunately this bug is not related to LAF itself, as i mentioned above the bug happens only with undecorated JFrame and rely to JVM here. This bug is not present on windows for instance.

Something really frustrating is that severals bugs affects the apple JVM implementation and you don't have any access to their internal bugs database to see if a bug has already been reported and its current status (begin fixed...).
I almost certain this bug is already known by Apple java dev team, i reported recently another important bug with their last 1.6.0_29 update which produce a memory leak with JViewport component :-/

To directly reply to your first question, no i did not find any workaround with that issue right now except preventing minimization.
