### ISSUE TITLE
Missing texts in JFileChooser

### ISSUE THREAD

**Issue by kdt** [Insubstantial/insubstantial#58]
Hi,
In some configurations javax.swing.JFileChooser does not have any UI texts.
I guess it's because the SubstanceFileChooserUI extends MetalFileChooserUI
and the original Metal resources are not loaded.
Instead it loads labels from various resources:

substance.jar:
org/pushingpixels/substance/internal/contrib/randelshofer/quaqua/Labels.properties

substance-lite.jar (works only with some locales, e.g. Locale.GERMAN):
org/pushingpixels/substance/internal/resources/Labels*.properties

I think the .../internal/resources/Labels.properties file
should contain default English FileChooser.xxx texts as well.

Thanks

**Comment by kdt** [comment]
Oh, and here is a small test that reproduces this bug :)
http://makagiga.sourceforge.net/playground/test/substance-jfilechooser-test.zip

**Comment by shemnon** [comment]
Thanks for the reproducible test case.  I was just about to close it as "needs more info."  The picture was the key.
