### ISSUE TITLE
Create separate classified Jars for Trident

### ISSUE THREAD

**Issue by shemnon** [Insubstantial/insubstantial#6]
The Trident jar currenly has all the support classes for all of the widget libraries it supports.  It would be good if we didn't have to ship jars for unsupported widget libraries.

Hence, we will create four additional classified jars.  One for each of the core widget libraries (android, swing, swt) and one for no widget library (base).  Each jar will have all that is needed for each but not the stuff that isn't needed.

**Comment by xvik** [comment]
Separation is not complete: in trident-6.3-*.jar/META-INF/trident-plugin.properties (where *== swing | swt |android) only specific UIToolkitHandler should stay. Currently it tries to load other handlers and fail with NoClassDefFound. 

Also (not a trident issue), trident sources are not downloaded now (under gradle idea module generation), do you know how to workaround it?

**Comment by shemnon** [comment]
fixed in #34
