### ISSUE TITLE
Substance L&F application automagically resizes with dual screen setup

### ISSUE THREAD

**Issue by hdijkema** [Insubstantial/insubstantial#77]
On Ubuntu 12.04, with java 7, my application (using substance 7.1) and also the demo (using substance 6.3) of the website of insubstantial, automagically resize (without warning) to a very small size, when I drag the window from one screen to another.

**Comment by shemnon** [comment]
This looks to be an Ubuntu/OpenJDK problem.  I am not inclined to put in special fixes for specific combinations of platforms, window managers, and jdk versions, as the error seems to be fixed by using the Oracle JVM:

http://forums.netbeans.org/topic47839.html

**Comment by hdijkema** [comment]
Hmm. a) I'm using the Oracle JVM; b) the other look and feels that I tested (nimbus, Gtk, System, metal, JGoodies) all work as expected.

**Comment by shemnon** [comment]
Well, I'de welcome a patch if that is the case.  I myself don't have to time to create a 2 monitor Ubuntu box and hunt down what is causing it.
