### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by jcorreia** [Insubstantial/insubstantial#79]
Hi,
thanks for keeping and update substance library :)
just some comments regarding your blog :
- Every I try to comment it says your space doesn´t exist...(maybe thats the reason theres no one because im sure many people is interested in your work)
- It doesn´t have a rss feed, so we can follow it, except if i log on, and I, like many, dont want to have to log to follow.

Thanks and keep the good work :)

**Comment by shemnon** [comment]
The theme was broken.  I chose a simpler one.

The RSS feed is http://insubstantial.posterous.com/rss.xml

**Comment by jcorreia** [comment]
Thanks J
