### ISSUE TITLE
black corners behind all my windows

### ISSUE THREAD

**Issue by veqryn** [Insubstantial/insubstantial#80]
Hi Shemnon, just want to say thanks for this project before I begin (and thanks for still supporting Java 6).

For a few years now my project (triplea) has been using Substance version 5.3.  I have been updating things and decided to update to the latest version, which appears to be your "insubstantial" version of Substance, version 7.1.

After including your 7.1 libraries, and changing the strings to use the new class paths for your libraries, and adding all the new skins that you have, I got it working.  It looks almost the same, but a little sharper and with rounded edges on my text and number boxes (cool).  

However, I noticed something bad: all of my windows now have black square corners "behind" the window.  It does not matter which skin I pick, all of them have it.  

I have tested this on my Windows 7 box (with aero/glass effects turned off cus I hate them), and also on my Windows Vista company computer, and both show the problem quite clearly.  I did notice that if I turned aero and glass back on, the problem went away (but only for Windows 7).

Substance 5.3 does not have this problem.

If I can't figure out how to attach pictures to this bug report, I'll email them to you.

thanks,
Chris

**Comment by veqryn** [comment]
To further investigate, I downloaded Substance 6.0, 6.3, 7.0, and 7.1

From testing all of them, I can tell you that the problem shows up only with 7.1, so it must be some change between 7.0 and 7.1

Good luck finding it, I hope for a new release with the fix soon, thanks!

I sent the pictures to your gmail account.

**Comment by shemnon** [comment]
turns out setting the window shape to null in windows 7 basic is not a 'reset' but a 'rectangle.'  If I see the window is decorated I now don't shape it.
