### ISSUE TITLE
Crash using color picker

### ISSUE THREAD

**Issue by elvencode** [Insubstantial/insubstantial#83]
Using JDK 1.7 on Windows 7 with Substance 6.3 (same problem also on 6.2) the default JColorChooser crashes inside the function updateImage of JSlider (reading the code this function seems only present in java 1.7). I removed the first (and second if i'm not wrong) color panel from the default ones placed inside the component and set a preview panel outside the JColorChooser to fix the problem.
I also placed a JSlider inside a panel to see if it's the component itself but it works correctly with Substance. I think that probably it's the "brightness" slider placed on the right of the gradients circle inside the color picker to have the problem.

PS with JDK 1.6 there's no crash
PS2  i use this look and feel  UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());

**Comment by shemnon** [comment]
I believe #26 fixed this, in insubstantial version 7.0.
