### ISSUE TITLE
Fatal error - Lite version is broken

### ISSUE THREAD

**Issue by Vity01** [Insubstantial/insubstantial#96]
We are not able to instantiate class SubstanceLookAndFeel , since it contains following code:

// initialize widget support
LafWidgetRepository.getRepository().setLafSupport(new SubstanceWidgetSupport());

but SubstanceWidgetSupport is a descendant of LafWidgetSupport which is not present in the lite-jar!

**Comment by shemnon** [comment]
You now need more than just the lite jar, I no longer package a monolithic jar for insubstantial.  You will also need laf-widget.jar, laf-plugin, and trident to run substance.  LafWidgetSupport is in the laf-widget jar.

**Comment by Vity01** [comment]
OK, but "lite" - is not lite then (when you need to also add so many other jars) ;-).

**Comment by shemnon** [comment]
It's lite because it strips out third party color choosers and the ant tasks, not because it's a monolith.

**Comment by Vity01** [comment]
OK. It works now. Thanks for help and maintaining this project.
